{
  "Description": "** DISPUTED ** A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0. NOTE: the vendor and discoverer indicate that this is not a security issue.",
  "Severity": "UNKNOWN",
  "Score": 0.0
}